# Generated by Django 4.2 on 2023-04-26 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=1000)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='market.profile')),
            ],
        ),
    ]
