# Generated by Django 4.2 on 2023-04-26 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='profile',
        ),
        migrations.AddField(
            model_name='item',
            name='creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='market.profile'),
        ),
    ]
