# Generated by Django 4.2 on 2023-04-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_alter_item_category_alter_item_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='creator',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
