# Generated by Django 4.2 on 2023-04-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_alter_item_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='creator',
            field=models.CharField(blank=True, default='admin', max_length=100),
        ),
    ]
