# Generated by Django 4.2 on 2023-04-26 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_alter_item_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='location',
        ),
        migrations.AlterField(
            model_name='item',
            name='creator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='market.profile'),
        ),
    ]
