# Generated by Django 4.2 on 2023-04-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_pub_photo_publication_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='photos',
        ),
        migrations.AddField(
            model_name='publication',
            name='photo',
            field=models.ImageField(default='pub_default-img.gif', upload_to=''),
        ),
        migrations.DeleteModel(
            name='Pub_photo',
        ),
    ]
