# Generated by Django 4.2 on 2023-04-27 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_remove_publication_photos_publication_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.profile'),
        ),
    ]
