# Generated by Django 4.2 on 2023-04-28 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_alter_publication_creator'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publication',
            new_name='Item',
        ),
    ]
