# Generated by Django 4.2 on 2023-04-29 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_rename_publication_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Address',
            new_name='address',
        ),
    ]
