# Generated by Django 4.2 on 2023-05-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
