# Generated by Django 4.2 on 2023-05-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0018_item_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.PositiveIntegerField(max_length=20000000),
        ),
    ]
